export const CHECK_START = 'CHECK_START'
export const CHECK_SUCCESS= 'CHECK_SUCCESS'
export const CHECK_FAIL= 'CHECK_FAIL'

export const ADD_GROCERY= 'ADD_GROCERY'
export const ADD_GROCERY_START= 'ADD_GROCERY_START'
export const ADD_GROCERY_FAIL= 'ADD_GROCERY_FAIL'
export const ADD_GROCERY_SUCCESS= 'ADD_GROCERY_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_GROCERIES = 'SET_GROCERIES'
export const FETCH_START = 'FETCH_START'
export const FETCH_FAIL ='FETCH_FAIL'

export const REMOVE_PIN= 'REMOVE_PIN'
export const ADD_PIN= 'ADD_PIN'

export const FETCH_MATES = 'FETCH_MATES'
export const FETCH_MATES_START = 'FETCH_MATES_START'
export const FETCH_MATES_SUCCESS = 'FETCH_MATES_SUCCESS'
export const FETCH_MATES_FAIL = 'FETCH_MATES_FAIL'

export const FETCH_FLAT_START = 'FETCH_FLAT_START'
export const FETCH_FLAT_FAIL = 'FETCH_FLAT_FAIL'
export const FETCH_FLAT_SUCCESS = 'FETCH_FLAT_SUCCESS'

export const ADD_MATE_START = 'ADD_MATE_START'
export const ADD_MATE_FAIL = 'ADD_MATE_FAIL'
export const ADD_MATE_SUCCESS = 'ADD_MATE_SUCCESS'