export const CHECK_ITEM = 'CHECK_ITEM'

export const ADD_GROCERY= 'ADD_GROCERY'
export const ADD_GROCERY_START= 'ADD_GROCERY_START'
export const ADD_GROCERY_FAIL= 'ADD_GROCERY_FAIL'
export const ADD_GROCERY_SUCCESS= 'ADD_GROCERY_SUCCESS'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const SET_GROCERIES = 'SET_GROCERIES'
export const FETCH_START = 'FETCH_START'
export const FETCH_FAIL ='FETCH_FAIL'

